name: Calculator App Validiations and tests

run-name: 'Calculator App Validiations and tests | Branch = ${{github.ref_name}}'

on:
  push:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read

jobs:
  frontend-validations:
    runs-on: ubuntu-latest 
    steps:
      - name: code-checkout
        uses: actions/checkout@v4 
      - name: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: code-validations
        run: |
          cd frontend
          npm ci
          npx htmlhint "**/*.html"
          npm run lint 
          npm run test:ci
  backend_valdiations:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: backend/
    steps:
      - name: code-checkout
        uses: actions/checkout@v4 
      - name: pyhton-setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install-dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements-dev.txt
      - name: backend-validations
        run: |
          make lint
          make test
  e2e_testing:
    runs-on: ubuntu-latest
    environment: e2e_testing
    steps:
      - name: code-checkout
        uses: actions/checkout@v4 
      - name: pyhton-setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: init-mysql-db
        run: |
          export MYSQL_HOST=${{env.MYSQL_HOST}}
          export MYSQL_DB=${{env.MYSQL_DB}}
          export MYSQL_USER=${{env.MYSQL_USER}}
          export MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}
          sudo systemctl start mysql.service
          cd database
          envsubst < init.sql.template \
                > init.sql

          envsubst < seed.sql.template \
                          > seed.sql
          
          cat init.sql 

          sudo mysql -h localhost -u root -proot < init.sql
          sudo mysql -h localhost -u root -proot < seed.sql

          